# src/main/resources/application-dev.yml
server:
  port: 18080

spring:
  data:
    redis:
      # 指向 192.168.30.x Linux 测试机的 Redis 容器 (或使用 SSH 映射填 127.0.0.1)
      host: 192.168.30.100
      port: 6379
      password: "" # 若容器未设密码可留空
  datasource:
    # 指向 192.168.30.x Linux 测试机的 MySQL 8.0 容器 (或使用 SSH 映射填 127.0.0.1:3306)
    url: jdbc:mysql://192.168.30.100:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: root

# 作为 28181 SIP 服务器的配置
sip:
  port: 8116
  # 主开发机（Windows 11）当前局域网物理网卡真实 IP
  ip: 192.168.30.252
  domain: 4101050000
  id: 41010500002000000001
  password: admin

media:
  id: zlmediakit-local
  # 指向 192.168.30.x Linux 测试机上运行的 ZLM 局域网 IP
  ip: 192.168.30.100
  http-port: 9092
  # [重点避坑] 明确通知 ZLM 回调 Windows 11 主开发机的 IP 地址
  hook-ip: 192.168.30.252
  # 与 ZLM 容器中的 secret 严格匹配
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  rtp:
    enable: true
    # 与 docker/infra/docker-compose.yml 暴露端口段 strictly 匹配
    port-range: 40000,40050
    send-port-range: 50000,55000

user-settings:
  auto-apply-play: true
  record-push-live: true
