# docker/aio/conf/redis-aio.conf
bind 127.0.0.1
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
pidfile /run/redis.pid
loglevel notice
logfile ""
databases 16
maxmemory 128mb
maxmemory-policy allkeys-lru
appendonly no
save ""
